name: release

on: 
  push:
    tags:
      - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up build args
          run: |
            echo "VERSION=${GITHUB_REF_NAME%-*}" >> $GITHUB_ENV
            echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: vergilgao
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: vergilgao
            password: ${{ secrets.GHCR_TOKEN }}

        - name: Build and push
          id: build_and_push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              vergilgao/webdav:${{ env.VERSION }}
              vergilgao/webdav:${{ env.TAG_VERSION }}
              vergilgao/webdav:latest
              ghcr.io/vergilgao/webdav:${{ env.VERSION }}
              ghcr.io/vergilgao/webdav:${{ env.TAG_VERSION }}
              ghcr.io/vergilgao/webdav:latest
            build-args: |
              VERSION=${{ env.VERSION }}
              BUILD_DATE=${{ env.BUILD_DATE }}
        
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}    